In [1]:
# dependencies
import pandas as pd

C:\Users\rod\anaconda3\envs\PythonData\lib\site-packages\ipykernel\parentpoller.py:116: UserWarning: Parent poll failed.  If the frontend dies,
                the kernel may be left running.  Please let us know
                about your system (bitness, Python, etc.) at
                ipython-dev@scipy.org
  ipython-dev@scipy.org""")

In [2]:
# store filepath in a variable
zoomfile = "resources/zoominfo.csv"

In [3]:
# Read our Data file with the pandas library
# Not every CSV requires an encoding, but be aware this can come up
zoom_org_df = pd.read_csv(zoomfile, encoding="ISO-8859-1")
zoom_df = zoom_org_df.copy()

In [4]:
# show the header
zoom_org_df.head()

,Intent ID,Date,Company Name,Topic,Category,Score,Recommended Contact ID,Recommended Contact First Name,Recommended Contact Last Name,Recommended Contact Title,...,Secondary Industry Hierarchical Category,Employees,LinkedIn Company Profile URL,Certified Active Company,Company Street Address,Company City,Company State,Company Zip Code,Company Country,Query Name
0,9061489b-b5bb-4cf7-b054-e552484adcda,9/12/2021 0:00,Greyspring Apartments,Cloud Migration,Cloud,100,4201290837,Karl,Brady,President,...,NaN,5,https://www.linkedin.com/company/greyspring-ap...,Yes,NaN,NaN,NaN,NaN,Canada,realestateexample
1,24d16a68-3ec6-4d55-a4e6-59df918f3645,9/12/2021 0:00,J & R Associates,Cloud Services,Cloud,99,5982552035,Huu,Duc,Computer Hardware Professional,...,NaN,5,https://www.linkedin.com/company/j-and-r-assoc...,Yes,364 41st St,Oakland,California,94609,United States,realestateexample
2,c706b774-4c86-4e38-a96d-5953db4458d8,9/5/2021 0:00,Vogels Buckman Appraisal Group,Cloud Services,Cloud,91,908609333,Patti,Hoppe,President,...,NaN,5,https://www.linkedin.com/company/vogels-buckma...,Yes,2005 S Webster Ave,Green Bay,Wisconsin,54301,United States,realestateexample
3,a16f51fb-cb09-40e9-9035-cfa14ce57d39,9/5/2021 0:00,XP Group,Data Center Management,Data Center,91,777770674,Meyer,Pinchassow,President,...,NaN,6,https://www.linkedin.com/company/meyer%27s-lat...,Yes,"1515 N University Dr, Ste 111",Coral Springs,Florida,33071,United States,realestateexample
4,9c9d478e-1f7d-4def-959c-bf9f20854a62,8/29/2021 0:00,Stone Mall,Data Center Management,Data Center,93,1733804875,Javier,Verdera,President,...,NaN,5,https://www.linkedin.com/company/stonemallusa/,Yes,350 Hillsboro Tecnology Dr,Deerfield Beach,Florida,33441,United States,realestateexample

In [5]:
# remove unnecessary columns
zoom_df = zoom_df.drop(['Date','Intent ID', 'Company ID','Category','Score','Recommended Contact ID'], axis=1)
zoom_df = zoom_df.drop(['Recommended Contact Notice Provided Date', 'Secondary Industry Hierarchical Category','Query Name'], axis=1)
zoom_df = zoom_df.drop(['Primary Industry', 'Primary Sub-Industry','All Industries','LinkedIn Company Profile URL'], axis=1)

In [6]:
zoom_df.head()

,Company Name,Topic,Recommended Contact First Name,Recommended Contact Last Name,Recommended Contact Title,Recommended Contact Phone (Direct),Recommended Contact Email,LinkedIn Contact Profile URL,Website,Company HQ Phone,Revenue (in 000s),All Sub-Industries,Industry Hierarchical Category,Employees,Certified Active Company,Company Street Address,Company City,Company State,Company Zip Code,Company Country
0,Greyspring Apartments,Cloud Migration,Karl,Brady,President,(647) 691-9550 ext. 543,karl.brady@greyspring.com,NaN,www.greyspring.com,(647) 691-9550,1326.0,NaN,realestate,5,Yes,NaN,NaN,NaN,NaN,Canada
1,J & R Associates,Cloud Services,Huu,Duc,Computer Hardware Professional,NaN,NaN,https://www.linkedin.com/in/huu-duc-le-912534a8,www.jras.com,(510) 547-8916,1322.0,NaN,realestate,5,Yes,364 41st St,Oakland,California,94609,United States
2,Vogels Buckman Appraisal Group,Cloud Services,Patti,Hoppe,President,NaN,NaN,NaN,vbappraisal.com,(920) 437-1717,1285.0,NaN,realestate,5,Yes,2005 S Webster Ave,Green Bay,Wisconsin,54301,United States
3,XP Group,Data Center Management,Meyer,Pinchassow,President,NaN,meyer@xpgroup.net,https://www.linkedin.com/in/meyer-pinchassow-2...,www.xpgroup.net,(954) 840-9000,1593.0,NaN,realestate,6,Yes,"1515 N University Dr, Ste 111",Coral Springs,Florida,33071,United States
4,Stone Mall,Data Center Management,Javier,Verdera,President,NaN,NaN,https://www.linkedin.com/in/javier-alfaro-verd...,www.stonemallusa.com,(954) 482-0499,1285.0,NaN,realestate,5,Yes,350 Hillsboro Tecnology Dr,Deerfield Beach,Florida,33441,United States

zooom_df.head()

In [7]:
zoom_df.shape

(37, 20)

In [8]:
# remove rows that have inactive companies -'certified active company'
# certified active companies =='Yes'
index_names = zoom_df[zoom_df['Certified Active Company']== 'No'].index
zoom_df.drop(index_names, inplace = True)
zoom_df.head()

,Company Name,Topic,Recommended Contact First Name,Recommended Contact Last Name,Recommended Contact Title,Recommended Contact Phone (Direct),Recommended Contact Email,LinkedIn Contact Profile URL,Website,Company HQ Phone,Revenue (in 000s),All Sub-Industries,Industry Hierarchical Category,Employees,Certified Active Company,Company Street Address,Company City,Company State,Company Zip Code,Company Country
0,Greyspring Apartments,Cloud Migration,Karl,Brady,President,(647) 691-9550 ext. 543,karl.brady@greyspring.com,NaN,www.greyspring.com,(647) 691-9550,1326.0,NaN,realestate,5,Yes,NaN,NaN,NaN,NaN,Canada
1,J & R Associates,Cloud Services,Huu,Duc,Computer Hardware Professional,NaN,NaN,https://www.linkedin.com/in/huu-duc-le-912534a8,www.jras.com,(510) 547-8916,1322.0,NaN,realestate,5,Yes,364 41st St,Oakland,California,94609,United States
2,Vogels Buckman Appraisal Group,Cloud Services,Patti,Hoppe,President,NaN,NaN,NaN,vbappraisal.com,(920) 437-1717,1285.0,NaN,realestate,5,Yes,2005 S Webster Ave,Green Bay,Wisconsin,54301,United States
3,XP Group,Data Center Management,Meyer,Pinchassow,President,NaN,meyer@xpgroup.net,https://www.linkedin.com/in/meyer-pinchassow-2...,www.xpgroup.net,(954) 840-9000,1593.0,NaN,realestate,6,Yes,"1515 N University Dr, Ste 111",Coral Springs,Florida,33071,United States
4,Stone Mall,Data Center Management,Javier,Verdera,President,NaN,NaN,https://www.linkedin.com/in/javier-alfaro-verd...,www.stonemallusa.com,(954) 482-0499,1285.0,NaN,realestate,5,Yes,350 Hillsboro Tecnology Dr,Deerfield Beach,Florida,33441,United States

In [9]:
# delete Certified Active Company column
zoom_df.drop(['Certified Active Company'], axis=1,inplace=True)
zoom_df.head()

,Company Name,Topic,Recommended Contact First Name,Recommended Contact Last Name,Recommended Contact Title,Recommended Contact Phone (Direct),Recommended Contact Email,LinkedIn Contact Profile URL,Website,Company HQ Phone,Revenue (in 000s),All Sub-Industries,Industry Hierarchical Category,Employees,Company Street Address,Company City,Company State,Company Zip Code,Company Country
0,Greyspring Apartments,Cloud Migration,Karl,Brady,President,(647) 691-9550 ext. 543,karl.brady@greyspring.com,NaN,www.greyspring.com,(647) 691-9550,1326.0,NaN,realestate,5,NaN,NaN,NaN,NaN,Canada
1,J & R Associates,Cloud Services,Huu,Duc,Computer Hardware Professional,NaN,NaN,https://www.linkedin.com/in/huu-duc-le-912534a8,www.jras.com,(510) 547-8916,1322.0,NaN,realestate,5,364 41st St,Oakland,California,94609,United States
2,Vogels Buckman Appraisal Group,Cloud Services,Patti,Hoppe,President,NaN,NaN,NaN,vbappraisal.com,(920) 437-1717,1285.0,NaN,realestate,5,2005 S Webster Ave,Green Bay,Wisconsin,54301,United States
3,XP Group,Data Center Management,Meyer,Pinchassow,President,NaN,meyer@xpgroup.net,https://www.linkedin.com/in/meyer-pinchassow-2...,www.xpgroup.net,(954) 840-9000,1593.0,NaN,realestate,6,"1515 N University Dr, Ste 111",Coral Springs,Florida,33071,United States
4,Stone Mall,Data Center Management,Javier,Verdera,President,NaN,NaN,https://www.linkedin.com/in/javier-alfaro-verd...,www.stonemallusa.com,(954) 482-0499,1285.0,NaN,realestate,5,350 Hillsboro Tecnology Dr,Deerfield Beach,Florida,33441,United States

In [10]:
zoom_df.shape

(32, 19)

In [11]:
# split HQ phone column into two columns df.Name.str.split("_",expand=True)
phone_split = zoom_df['Recommended Contact Phone (Direct)'].str.split("e",expand=True)
phone_split

                  0        1
0   (647) 691-9550   xt. 543
1               NaN      NaN
2               NaN      NaN
3               NaN      NaN
4               NaN      NaN
5    (425) 438-1811     None
7               NaN      NaN
8               NaN      NaN
9   (614) 486-8911     xt. 1
10              NaN      NaN
12              NaN      NaN
13   (858) 271-0582     None
14  (858) 271-0582   xt. 142
15              NaN      NaN
16              NaN      NaN
17   (617) 528-0277     None
18              NaN      NaN
19              NaN      NaN
20              NaN      NaN
21              NaN      NaN
22              NaN      NaN
23   (212) 686-9476     None
26              NaN      NaN
27   (732) 942-0766     None
28              NaN      NaN
29              NaN      NaN
30              NaN      NaN
31   (305) 647-9484     None
32              NaN      NaN
34   (651) 383-1181     None
35              NaN      NaN
36   (651) 383-1181     None

In [12]:
# store split phone number in zoom_df
zoom_df['Contact- Direct Phone']=phone_split[0]
zoom_df['Contact- Direct Extension']=phone_split[1]

In [13]:
# split Company Street Address column into two columns (adddress & suite no.)
address_split = zoom_df['Company Street Address'].str.split(",",expand=True)
address_split

                              0                 1
0                           NaN               NaN
1                   364 41st St              None
2            2005 S Webster Ave              None
3          1515 N University Dr           Ste 111
4    350 Hillsboro Tecnology Dr              None
5   1610 SE Everett Mall Way Ã‚Â·              None
7               12000 Starcrest           Ste 111
8               12000 Starcrest           Ste 111
9                1635 W 1st Ave           Ste 140
10              815 S Gaffey St              None
12            2554 Lincoln Blvd   Ste 1032NMARINA
13            2554 Lincoln Blvd   Ste 1032NMARINA
14            2554 Lincoln Blvd   Ste 1032NMARINA
15            107 Northern Blvd           Ste 311
16           1200 N Federal Hwy           Ste 200
17                 277 Broadway              None
18                  11751 Cr 12              None
19               333 W Broadway              #210
20              800 LaSalle Ave          Ste 1210
21                  PO Box 6125              None
22       666 Sherbrooke St West          Ste 2300
23              232 Madison Ave              None
26                 Brickhill Dr              None
27             184 New Egypt Rd              None
28             184 New Egypt Rd              None
29            229 N Bartlett St              None
30               5330 Derry Ave             Ste K
31            1825 NW 112TH Ave           Ste 153
32        11 1-2 West Winter St              None
34          1600 University Ave           Ste 212
35                507 W High St              None
36          1600 University Ave           Ste 212

In [14]:
# store split address in zoom_df
zoom_df['Company- Address- Line 1']=address_split[0]
zoom_df['Company- Address- Line 2']=address_split[1]

In [15]:
zoom_df.columns

Index(['Company Name', 'Topic', 'Recommended Contact First Name',
       'Recommended Contact Last Name', 'Recommended Contact Title',
       'Recommended Contact Phone (Direct)', 'Recommended Contact Email',
       'LinkedIn Contact Profile URL', 'Website', 'Company HQ Phone',
       'Revenue (in 000s)', 'All Sub-Industries',
       'Industry Hierarchical Category', 'Employees', 'Company Street Address',
       'Company City', 'Company State', 'Company Zip Code', 'Company Country',
       'Contact- Direct Phone', 'Contact- Direct Extension',
       'Company- Address- Line 1', 'Company- Address- Line 2'],
      dtype='object')

In [16]:
# delete columns that were split in two
# address column and phone column
zoom_df.drop(['Recommended Contact Phone (Direct)','Company Street Address',], axis=1,inplace=True)
# drop remaining unnecessary columns
zoom_df.drop(['All Sub-Industries','Industry Hierarchical Category',], axis=1,inplace=True)

In [17]:
zoom_df.columns

Index(['Company Name', 'Topic', 'Recommended Contact First Name',
       'Recommended Contact Last Name', 'Recommended Contact Title',
       'Recommended Contact Email', 'LinkedIn Contact Profile URL', 'Website',
       'Company HQ Phone', 'Revenue (in 000s)', 'Employees', 'Company City',
       'Company State', 'Company Zip Code', 'Company Country',
       'Contact- Direct Phone', 'Contact- Direct Extension',
       'Company- Address- Line 1', 'Company- Address- Line 2'],
      dtype='object')

In [18]:
zoom_df.shape

(32, 19)

In [19]:
# rename current columns to connectwise format
zoom_df.rename(columns={'Topic': 'Company- Note',
                        'Recommended Contact First Name': 'Contact- First Name',
                        'Recommended Contact Last Name': 'Contact- Last Name',
                        'Recommended Contact Title':'Contact- Job Title',
                        'Recommended Contact Email':'Contact- Email address',
                        'LinkedIn Contact Profile URL':'Contact- Note',
                        'Website':'Company- Website URL',
                        'Company HQ Phone':'Company- Phone Number',
                        'Revenue (in 000s)':'Company- Annual Revenue',
                        'Employees':'Company- Number of employees',
                        'Company City':'Company- City',
                        'Company State':'Company- State',
                        'Company Zip Code':'Company- Zip',
                        'Company Country':'Company- Country'                     
                        },
          inplace=True, errors='raise')

In [20]:
zoom_df.columns

Index(['Company Name', 'Company- Note', 'Contact- First Name',
       'Contact- Last Name', 'Contact- Job Title', 'Contact- Email address',
       'Contact- Note', 'Company- Website URL', 'Company- Phone Number',
       'Company- Annual Revenue', 'Company- Number of employees',
       'Company- City', 'Company- State', 'Company- Zip', 'Company- Country',
       'Contact- Direct Phone', 'Contact- Direct Extension',
       'Company- Address- Line 1', 'Company- Address- Line 2'],
      dtype='object')

In [21]:
zoom_df['Company ID']=''
zoom_df['Company- Fax Number']=''
zoom_df['Company- Site Name']=''
zoom_df['Company- SIC code']=''
zoom_df['Company- Tax ID']=''
zoom_df['Company- Tax Code']=''
zoom_df['Company- Account']=''
zoom_df['Company- Vendor ID']=''
zoom_df['Company- Member ID for the Territory Manager']=''
zoom_df['Contact- Home phone']=''
zoom_df['Contact- Cell Phone']=''
zoom_df['Contact- Activity Assign To Member']=''
zoom_df['Contact- Activity Subject']=''
zoom_df['Primary Contact']=''
zoom_df['Billing Contact']=''

In [22]:
zoom_df.head()

,Company Name,Company- Note,Contact- First Name,Contact- Last Name,Contact- Job Title,Contact- Email address,Contact- Note,Company- Website URL,Company- Phone Number,Company- Annual Revenue,...,Company- Tax Code,Company- Account,Company- Vendor ID,Company- Member ID for the Territory Manager,Contact- Home phone,Contact- Cell Phone,Contact- Activity Assign To Member,Contact- Activity Subject,Primary Contact,Billing Contact
0,Greyspring Apartments,Cloud Migration,Karl,Brady,President,karl.brady@greyspring.com,NaN,www.greyspring.com,(647) 691-9550,1326.0,...,,,,,,,,,,
1,J & R Associates,Cloud Services,Huu,Duc,Computer Hardware Professional,NaN,https://www.linkedin.com/in/huu-duc-le-912534a8,www.jras.com,(510) 547-8916,1322.0,...,,,,,,,,,,
2,Vogels Buckman Appraisal Group,Cloud Services,Patti,Hoppe,President,NaN,NaN,vbappraisal.com,(920) 437-1717,1285.0,...,,,,,,,,,,
3,XP Group,Data Center Management,Meyer,Pinchassow,President,meyer@xpgroup.net,https://www.linkedin.com/in/meyer-pinchassow-2...,www.xpgroup.net,(954) 840-9000,1593.0,...,,,,,,,,,,
4,Stone Mall,Data Center Management,Javier,Verdera,President,NaN,https://www.linkedin.com/in/javier-alfaro-verd...,www.stonemallusa.com,(954) 482-0499,1285.0,...,,,,,,,,,,

In [23]:
# change order of column names to match connectwise templatezoom
column_names = ['Company Name',
'Company ID',
'Company- Phone Number',
'Company- Fax Number',
'Company- Site Name',
'Company- Address- Line 1',
'Company- Address - Line 2',
'Company- City',
'Company- State',
'Company- Zip',
'Company- Country',
'Company- Website URL',
'Company- Annual Revenue',
'Company- Number of employees',
'Company- SIC code',
'Company- Tax ID',
'Company- Tax Code',
'Company- Account',
'Company- Vendor ID',
'Company- Note',
'Company- Member ID for the Territory Manager',
'Contact- First Name',
'Contact- Last Name',
'Contact- Job Title',
'Contact- Direct Phone',
'Contact- Direct Extension',
'Contact- Email address',
'Contact- Home phone',
'Contact- Cell Phone',
'Contact- Note',
'Contact- Activity Assign To Member',
'Contact- Activity Subject',
'Primary Contact',
'Billing Contact']

zoom_df = zoom_df.reindex(columns=column_names)

In [24]:
zoom_df.columns

Index(['Company Name', 'Company ID', 'Company- Phone Number',
       'Company- Fax Number', 'Company- Site Name', 'Company- Address- Line 1',
       'Company- Address - Line 2', 'Company- City', 'Company- State',
       'Company- Zip', 'Company- Country', 'Company- Website URL',
       'Company- Annual Revenue', 'Company- Number of employees',
       'Company- SIC code', 'Company- Tax ID', 'Company- Tax Code',
       'Company- Account', 'Company- Vendor ID', 'Company- Note',
       'Company- Member ID for the Territory Manager', 'Contact- First Name',
       'Contact- Last Name', 'Contact- Job Title', 'Contact- Direct Phone',
       'Contact- Direct Extension', 'Contact- Email address',
       'Contact- Home phone', 'Contact- Cell Phone', 'Contact- Note',
       'Contact- Activity Assign To Member', 'Contact- Activity Subject',
       'Primary Contact', 'Billing Contact'],
      dtype='object')

In [25]:
zoom_df.head()

,Company Name,Company ID,Company- Phone Number,Company- Fax Number,Company- Site Name,Company- Address- Line 1,Company- Address - Line 2,Company- City,Company- State,Company- Zip,...,Contact- Direct Phone,Contact- Direct Extension,Contact- Email address,Contact- Home phone,Contact- Cell Phone,Contact- Note,Contact- Activity Assign To Member,Contact- Activity Subject,Primary Contact,Billing Contact
0,Greyspring Apartments,,(647) 691-9550,,,NaN,NaN,NaN,NaN,NaN,...,(647) 691-9550,xt. 543,karl.brady@greyspring.com,,,NaN,,,,
1,J & R Associates,,(510) 547-8916,,,364 41st St,NaN,Oakland,California,94609,...,NaN,NaN,NaN,,,https://www.linkedin.com/in/huu-duc-le-912534a8,,,,
2,Vogels Buckman Appraisal Group,,(920) 437-1717,,,2005 S Webster Ave,NaN,Green Bay,Wisconsin,54301,...,NaN,NaN,NaN,,,NaN,,,,
3,XP Group,,(954) 840-9000,,,1515 N University Dr,NaN,Coral Springs,Florida,33071,...,NaN,NaN,meyer@xpgroup.net,,,https://www.linkedin.com/in/meyer-pinchassow-2...,,,,
4,Stone Mall,,(954) 482-0499,,,350 Hillsboro Tecnology Dr,NaN,Deerfield Beach,Florida,33441,...,NaN,NaN,NaN,,,https://www.linkedin.com/in/javier-alfaro-verd...,,,,

In [27]:
# multiply revenue column by scaler
zoom_df['Company- Annual Revenue'] = zoom_df['Company- Annual Revenue'] * 1000

In [28]:
zoom_df['Company- Annual Revenue']

0     1326000.0
1     1322000.0
2     1285000.0
3     1593000.0
4     1285000.0
5     2316000.0
7     2066000.0
8     2066000.0
9     2583000.0
10    1313000.0
12    1319000.0
13    1319000.0
14    1319000.0
15    1545000.0
16    1568000.0
17    1305000.0
18    1307000.0
19    1595000.0
20    1326000.0
21    2390000.0
22    2104000.0
23    2118000.0
26    1327000.0
27    1583000.0
28    1583000.0
29    2610000.0
30    1306000.0
31    1538000.0
32    1820000.0
34    1571000.0
35          NaN
36    1571000.0
Name: Company- Annual Revenue, dtype: float64

In [26]:
# export to connect wise .csv file
zoom_df.to_csv('resources/cw.csv', index=False)